[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bombergame/common"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.2"
