required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/tools/cmd/cover",
  "github.com/mattn/goveralls"
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bombergame/common"
