[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bombergame/common"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"
